### ISSUE TITLE
Can't generate user openvpn configs

### ISSUE THREAD

**Issue by MarkCumminsIRL** [nategraf/ctfd-naumachia-plugin#2]
Trying to use the plugin with current version of CTFd. 

Plugin appears as a challenge option however when i go to click on the link to download the config i get an internal server error.

I've edited the config.py to include my server ip... is there something else i'm missing?

also if i later want to force tls do I just need to set tls true and copy the cert to my ctfd server? 

Sorry for silly questions...

**Comment by nategraf** [comment]
I don't really have enough information to help you from this, so here are some questions:
1. When you say "your server ip" you mean the ip of your running naumachia instance, correct?
2. Are you running CTFd and Naumachia on different hosts, the same host.. what is your setup?

Also, TLS client certs are currently not supported in this plugin, but could be added if you want to write the PR!

These aren't silly questions! 😄

**Comment by MarkCumminsIRL** [comment]
So yes i'm using the server ip of my Naumachia server and default port.
and yes i currently have CTFD and Naumachia running on separate servers.. 

any ideas?

I've gotten this from CTFD...
ctfd_1   | [2019-03-20 02:52:07,554] ERROR in app: Exception on /naumachia/config/4 [GET]
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
ctfd_1   |     response = self.full_dispatch_request()
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
ctfd_1   |     rv = self.handle_user_exception(e)
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/flask_restplus/api.py", line 583, in error_router
ctfd_1   |     return original_handler(e)
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
ctfd_1   |     reraise(exc_type, exc_value, tb)
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
ctfd_1   |     rv = self.dispatch_request()
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
ctfd_1   |     return self.view_functions[rule.endpoint](**req.view_args)
ctfd_1   |   File "/opt/CTFd/CTFd/plugins/ctfd-naumachia-plugin/__init__.py", line 261, in registrar
ctfd_1   |     resp = send_config(host, escaped_chalname, escaped_username)
ctfd_1   |   File "/opt/CTFd/CTFd/plugins/ctfd-naumachia-plugin/__init__.py", line 216, in send_config
ctfd_1   |     resp = urlopen(url, timeout=registrar_timeout)
ctfd_1   |   File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
ctfd_1   |     return opener.open(url, data, timeout)
ctfd_1   |   File "/usr/local/lib/python2.7/urllib2.py", line 429, in open
ctfd_1   |     response = self._open(req, data)
ctfd_1   |   File "/usr/local/lib/python2.7/urllib2.py", line 447, in _open
ctfd_1   |     '_open', req)
ctfd_1   |   File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
ctfd_1   |     result = func(*args)
ctfd_1   |   File "/usr/local/lib/python2.7/urllib2.py", line 1228, in http_open
ctfd_1   |     return self.do_open(httplib.HTTPConnection, req)
ctfd_1   |   File "/usr/local/lib/python2.7/urllib2.py", line 1201, in do_open
ctfd_1   |     r = h.getresponse(buffering=True)
ctfd_1   |   File "/usr/local/lib/python2.7/httplib.py", line 1121, in getresponse
ctfd_1   |     response.begin()
ctfd_1   |   File "/usr/local/lib/python2.7/httplib.py", line 438, in begin
ctfd_1   |     version, status, reason = self._read_status()
ctfd_1   |   File "/usr/local/lib/python2.7/httplib.py", line 394, in _read_status
ctfd_1   |     line = self.fp.readline(_MAXLINE + 1)
ctfd_1   |   File "/usr/local/lib/python2.7/socket.py", line 480, in readline
ctfd_1   |     data = self._sock.recv(self._rbufsize)
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/gevent/_socket2.py", line 289, in recv
ctfd_1   |     return sock.recv(*args)
ctfd_1   | error: [Errno 104] Connection reset by peer

**Comment by nategraf** [comment]
So the "connection reset by peer" implies to me that port 3960 is not open on the Naumachia server. Make sure you can access the Naumachia registrar API via curl from your CTFd host. Something like `curl $NAUMACHIA_HOST:3960/example/list`

**Comment by MarkCumminsIRL** [comment]
Cheers pointed me in the right direction...
I had silly mistake in my initial config.yaml
I had tls enabled... never read the example config file properly.. all working now cheers!!    
tls_enabled: true
tls_verify_client: true
